### ISSUE TITLE
Fatal Error: 'Uncaught Error: Call to a member function getFirstName() on null

### ISSUE THREAD

**Issue by YoSoyPhil** [RBech/QuickPay_Magento2#7]
First, thank you for your work!
Second, I have a problem seemingly in my Magento 2.2.4 (Luma theme) installation in regards to QuickPay.
I have put a product in cart, filled my address info, pressed update (on address) and then "Place Order".
Afterwards I get a small empty error msg on frontend and checking api calls gave me this (in reports/api):
```
"Fatal Error: 'Uncaught Error: Call to a member function getFirstName() on null in /vendor/quickpay/magento2/Model/Adapter/QuickPayAdapter.php:97
Stack trace:
#0 /vendor/quickpay/magento2/Gateway/Http/Client/TransactionAuthorize.php(12): QuickPay/Payment/Model/Adapter/QuickPayAdapter->authorizeAndCreatePaymentLink(Array)
#1 /vendor/quickpay/magento2/Gateway/Http/Client/AbstractTransaction.php(57): QuickPay/Payment/Gateway/Http/Client/TransactionAuthorize->process(Array)
#2 /app/code/Magento/Payment/Gateway/Command/GatewayCommand.php(102): QuickPay/Payment/Gateway/Http/Client/AbstractTransaction->placeRequest(Object(Magento/Payment/Gateway/Http/Transfer))
#3 /app/code/Magento/Payment/Model/Method/Adapter.php(546): Magento/Payment/Gateway/Command/GatewayCommand->execute(Array)
#4 /app/code/Magento/Payment/Model/Method/Adapter.php(448): Magento/Payment/Model/Method/Adapter->executeComm' in '/vendor/quickpay/magento2/Model/Adapter/QuickPayAdapter.php' on line 97"
``` 

PHP 7.1.17 
nginx/1.12.2

Hope you can help me get this sorted, thanks in advance if so 👍

**Comment by VirtusB** [comment]
Error is fixed: https://github.com/RBech/QuickPay_Magento2/pull/8
